### ISSUE TITLE
Is it possible to add support for spring @PropertySource

### ISSUE THREAD

**Issue by dzahusta** [yyvess/jsconf#1]
Is it possible to add support for spring @PropertySource to use standard @Value annotation? It would be really awesome.

**Comment by yyvess** [comment]
Sorry for the delay ...
It's a good idea, but I not sure that we can integrate with @PropertySource.
If you check [Spring-boot Externalized Configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html), they did not support @PropertySource.
