### ISSUE TITLE
specifiy import in README 

### ISSUE THREAD

**Issue by gargarozz** [yyvess/jsconf#2]
Hi,
the following dependency is necessary in the pom
` <dependency>
             <groupId>commons-dbcp</groupId>
             <artifactId>commons-dbcp</artifactId>
             <version>1.4</version>
         </dependency>
`

in order to use 
BasicDataSource.class 
as specificied in the README

**Comment by gargarozz** [comment]
ah ok, it's just the example class in the example. it's not needed in general. 
Do you have to list all the beans, or is there a way to say "fetch all the beans" ?

**Comment by yyvess** [comment]
If you beans if annoted with @ConfigurationProperties,  you can use withScanPackage insiste of liste all beans.
See the Sample02.
