### ISSUE TITLE
Bean list

### ISSUE THREAD

**Issue by aclowkey** [yyvess/jsconf#3]
Hi,

I'm trying to use jsconf to read a list of my own type beans.
i.e. List of People : get List of People class from the JSON:
{
   "People":[ { "name":"Alex"},{ "name":"John"}]
}

Is it possible to do with jsconf ? thanks.

**Comment by oligatorr** [comment]
For your information I have done this. Nothing particular except that you might need to creat Spring Converter to tell Spring how to map hashmap to the type which accept your "name" attribute.
